### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by gpsmith1** [wboxx1/85-EIS-PUMA#48]
When I download source code there are several errors.

GPS.dll   not found    I found a copy and linked it

ADAM6060_AGILENT87106 not found

Error	47	'getNumChannels' is not a member of 'System.Diagnostics.Switch'.	C:\Users\emc1\Documents\Visual Studio 2013\Projects\85-EIS-PUMA-1.7.6\Supporting Controllers\AntennaSwitch.vb	51	34	PUMA

**Comment by wboxx1** [comment]
The source code does not include the dlls.  You must install the version of the program first.  This will install the appropriate dlls.  Then you can use the source code.
