### ISSUE TITLE
Replay Enhancements

### ISSUE THREAD

**Issue by gpsmith1** [wboxx1/85-EIS-PUMA#73]
This is an expansion of issue #44
**GPS accuracy**. GPS location in PUMA 1.7.7 is rounded to decimal degrees with 4 digits. .0001 degree is 11 meters (or less for higher in latitude longitudes) We need 5 digits to resolve 1.1 meters. This is an issue in the GUI and the exported replay CSVs.
**Replay Azimuth Data**. Replay needs to track the azimuth associated with the max amplitude for each data point.( I think it used to long ago) The Max Azimuth for each point should wind up in the exported CSV files. MAX Azimuth should also be accessible  via the Cursor after reply runs and while it is paused or running.
**Azimuth Profile**It would be desirable to be able to replay azimuth vs amlitude for specific frequencies in the data (such as where a marker/cursor is set .) this may provide a weighted azimuth that is more accurate than just the max. It is similar to how signal finder operates.
**GPS averaging**.  For most surveys the location is constant for a test point. Tracking GPS during  replay may provide better accuracy by providing Average position, Mean?, and deviation information.

**Comment by wboxx1** [comment]
Azimuth Profile already a feature in separate plot replay.
